name: Test

on:
  workflow_dispatch:

jobs:
  test:
    # Где запускаем
    runs-on: ubuntu-latest

    # Что делаем
    steps:
      # Настраиваем GitHub Action и решаем проблемы с безопасной директорией
      - name: Configure Git safe directory
        run: git config --global --add safe.directory /home/runner/work/new-lesson-15-allure/new-lesson-15-allure

      # Выкачиваем репозиторий
      - name: Checkout repository (main branch)
        uses: actions/checkout@v3
        with:
          ref: main

      # Настраиваем Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      # Запускаем Selenoid
      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2

      # Запускаем тесты
      - name: Run tests
        run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      # Скачиваем историю тестов из ветки gh-pages
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Генерируем отчет Allure
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      # Публикуем отчет на GitHub Pages
      - name: Publish Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        if: always()
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
